name: efood_table_booking
description: A new Flutter application.
publish_to: 'none' #
version: 1.0.0+1

environment:
  sdk: ">=2.17.1 <3.0.0"


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.5
  get: ^4.6.5
  intl: ^0.17.0
  shared_preferences: ^2.0.15
  connectivity_plus: ^3.0.2
  firebase_core: ^2.2.0
  firebase_messaging: ^14.1.0
  flutter_local_notifications: ^12.0.3
  path_provider: ^2.0.11
  url_strategy: ^0.2.0
  image_picker: ^0.8.5+3
  cached_network_image: ^3.2.2
  lottie: ^2.0.0
  flutter_custom_clippers: ^2.0.0
  youtube_player_flutter: ^8.1.2
  carousel_slider: ^4.1.1
  shimmer: ^2.0.0
  country_code_picker: ^3.0.0

  fluttertoast: ^8.0.9
  getwidget: ^3.0.1
  expandable_text: ^2.3.0
  flutter_riverpod: ^2.1.3
  dartz: ^0.10.1
  fab_circular_menu: ^1.0.2
  universal_platform: ^1.0.0+1
  modal_bottom_sheet: ^2.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:
  uses-material-design: true

  assets:
    - assets/image/
    - assets/language/

  fonts:
    - family: Roboto
      fonts:
        - asset: assets/font/Roboto-Regular.ttf
          weight: 400
        - asset: assets/font/Roboto-Medium.ttf
          weight: 500
        - asset: assets/font/Roboto-Bold.ttf
          weight: 700
        - asset: assets/font/Roboto-Black.ttf
          weight: 900